action = {'0': 'STATUS_NONE',
        '1': 'STATUS_PASS',
        '2': 'STATUS_DELETE',
        '3': 'STATUS_DELETE_ALL',
        '4': 'STATUS_REPLACE',
        '5': 'STATUS_QUARANTINE',
        '6': 'STATUS_CLEAN',
        '7': 'STATUS_TAG',
        '8': 'STATUS_TMP_QUARANTINE',
        '9': 'STATUS_MOVE_TO_JUNK_FOLDER',
        'failed': 'failed'}
filter = {'0': 'ID_FILTERTYPE_UNKNOWN',
          '1': 'ID_FILTERTYPE_VIRUS_SCANNING',
          '2': 'ID_FILTERTYPE_DDAaaS',
          '4': 'ID_FILTERTYPE_FILE_BLOCKING',
          '8': 'ID_FILTERTYPE_ANTISPAM',
          '128': 'ID_FILTERTYPE_WEB_THREAT_PROTECTION',
          '512': 'ID_FILTERTYPE_DLP',
          'failed': 'failed'}