# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageInterface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messageInterface.proto',
  package='',
  serialized_pb=_b('\n\x16messageInterface.proto\"\x83\x01\n\tBlockUnit\x12\x10\n\x08partType\x18\x01 \x01(\t\x12\x14\n\x0c\x65ncodingType\x18\x02 \x01(\t\x12\x18\n\x10\x62lockDescription\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\r\x12\x13\n\x0bstrReserves\x18\x06 \x03(\t\"G\n\rTransportUnit\x12\x13\n\x0bstrItemList\x18\x01 \x03(\t\x12!\n\rblockItemList\x18\x02 \x03(\x0b\x32\n.BlockUnit\"/\n\x0e\x44\x61taCollection\x12\x1d\n\x05units\x18\x01 \x03(\x0b\x32\x0e.TransportUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLOCKUNIT = _descriptor.Descriptor(
  name='BlockUnit',
  full_name='BlockUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partType', full_name='BlockUnit.partType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encodingType', full_name='BlockUnit.encodingType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blockDescription', full_name='BlockUnit.blockDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='BlockUnit.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='BlockUnit.action', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strReserves', full_name='BlockUnit.strReserves', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=158,
)


_TRANSPORTUNIT = _descriptor.Descriptor(
  name='TransportUnit',
  full_name='TransportUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strItemList', full_name='TransportUnit.strItemList', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blockItemList', full_name='TransportUnit.blockItemList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=231,
)


_DATACOLLECTION = _descriptor.Descriptor(
  name='DataCollection',
  full_name='DataCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='DataCollection.units', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=280,
)

_TRANSPORTUNIT.fields_by_name['blockItemList'].message_type = _BLOCKUNIT
_DATACOLLECTION.fields_by_name['units'].message_type = _TRANSPORTUNIT
DESCRIPTOR.message_types_by_name['BlockUnit'] = _BLOCKUNIT
DESCRIPTOR.message_types_by_name['TransportUnit'] = _TRANSPORTUNIT
DESCRIPTOR.message_types_by_name['DataCollection'] = _DATACOLLECTION

BlockUnit = _reflection.GeneratedProtocolMessageType('BlockUnit', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKUNIT,
  __module__ = 'messageInterface_pb2'
  # @@protoc_insertion_point(class_scope:BlockUnit)
  ))
_sym_db.RegisterMessage(BlockUnit)

TransportUnit = _reflection.GeneratedProtocolMessageType('TransportUnit', (_message.Message,), dict(
  DESCRIPTOR = _TRANSPORTUNIT,
  __module__ = 'messageInterface_pb2'
  # @@protoc_insertion_point(class_scope:TransportUnit)
  ))
_sym_db.RegisterMessage(TransportUnit)

DataCollection = _reflection.GeneratedProtocolMessageType('DataCollection', (_message.Message,), dict(
  DESCRIPTOR = _DATACOLLECTION,
  __module__ = 'messageInterface_pb2'
  # @@protoc_insertion_point(class_scope:DataCollection)
  ))
_sym_db.RegisterMessage(DataCollection)


# @@protoc_insertion_point(module_scope)
